inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"

# contextを日本語で書けるようにする
RSpec/ContextWording:
  Enabled: false